apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: my-test-operators
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/ajeetas/cia-ingress-index:v1.2.7_2
  displayName: Test Operators2
  publisher: Red Hat Partner
  updateStrategy:
    registryPoll:
      interval: 5m
