apiVersion: citrix.citrix.com/v1alpha1
kind: Citrix-adc-istio-ingress-gateway
metadata:
  name: citrix-adc-istio-ingress-gateway-sample
spec:
  # Default values copied from <project_dir>/helm-charts/citrix-adc-istio-ingress-gateway/values.yaml
  citrixCPX: false
  ingressGateway:
    EULA: false
    exposeMutipleApps: false
    exposeNonHttpService: false
    httpNodePort: 30180
    httpsNodePort: 31443
    image: quay.io/citrix/citrix-k8s-cpx-ingress
    imagePullPolicy: IfNotPresent
    label: citrix-ingressgateway
    licenseServerPort: 27000
    lightWeightCPX: 1
    mgmtHttpPort: 10080
    mgmtHttpsPort: 10443
    secretVolumes:
      mountPath: null
      name: null
      secretName: null
    tag: 13.0-47.22
    tcpPort:
      name: null
      nodePort: null
      port: null
      targetPort: null
  istioAdaptor:
    ADMFingerPrint: null
    ADMIP: null
    coeURL: null
    image: quay.io/citrix/citrix-istio-adaptor
    imagePullPolicy: IfNotPresent
    netProfile: null
    netscalerUrl: null
    proxyType: router
    secureConnect: false
    tag: 1.2.2
    vserverIP: null
  istioPilot:
    SAN: spiffe://cluster.local/ns/istio-system/sa/istio-pilot-service-account
    insecureGrpcPort: 15010
    name: istio-pilot
    namespace: istio-system
    secureGrpcPort: 15011
  metricExporter:
    image: quay.io/citrix/citrix-adc-metrics-exporter
    imagePullPolicy: IfNotPresent
    logLevel: ERROR
    port: 8888
    required: true
    secure: "YES"
    version: 1.4.0
  
  
