apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.0.1
    operators.operatorframework.io/project_layout: helm.sdk.operatorframework.io/v1
  name: citrix-adc-istio-ingress-gateway-operator.vX.Y.Z
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: An Istio ingress gateway acts as an entry point for the incoming traffic and secures and controls access to the service mesh from outside. It also performs routing and load balancing. Citrix ADC CPX, MPX, or VPX can be deployed as an ingress gateway to the Istio service mesh
  displayName: Citrix ADC Istio Ingress Gateway Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - Ajeeta Shakeet:ajeeta.shakeet@citrix.com
  links:
  - name: Citrix Adc Istio Ingress Gateway Operator
    url: https://citrix-adc-istio-ingress-gateway-operator.domain
  maturity: alpha
  provider:
    name: citrix
    url: citrix.com
  version: 0.0.0
